#!/bin/sh  
# \
exec tclsh "$0" "$@"

proc APSStrictParseArguments {optlist} {
    upvar args arguments
    set length [llength $arguments]
    set index 0
    set leftovers {}
    while {$index<$length} {
	set arg [lindex $arguments $index]
	if {[string index $arg 0]=="-"} {
	    set keywordName [string range $arg 1 end]
	    if {[lsearch -exact $optlist $keywordName]!=-1} {
		incr index
		if {$index==$length} {
		    lappend leftovers $arg
		} else {
		    set valueString [lindex $arguments $index]
		    uplevel "set $keywordName {$valueString}"
		    incr index
		}
	    } else {
		incr index
		lappend leftovers $arg
	    }
	} else {
	    lappend leftovers $arg
	    incr index
	}
    }
    set arguments [concat $leftovers]
    if {$arguments != ""} {
	set procName [lindex [info level [expr {[info level] - 1}]] 0]
	puts stderr "Unknown option(s) given to $procName \"$arguments\""
	return -1
    } else {
	return 0
    }
}


proc APSClearOptions {} {
    upvar args arguments
    set length [llength $arguments]
    set index 0
    set leftovers {}
    while {$index<$length} {
	set arg [lindex $arguments $index]
	if {[string index $arg 0]=="-"} {
	    incr index 2
	} else {
	    lappend leftovers $arg
	    incr index
	}
    }
    set arguments [concat $leftovers]
}

set usage {usage: plotCompress -rootname <string> [-device <name>] [-printer <name>] [-output <filename>]}
set args $argv
set rootname ""
set device motif
set output ""
set printer ""
set sparse 1
if {[APSStrictParseArguments {rootname device printer output sparse}]} {
    puts stderr $usage
    exit 1
}
if [string length $rootname]==0 {
    puts stderr "Supply rootname"
    exit 1
}
if {[string length $printer] && [string length $output]} {
    puts stderr "Supply printer or output file, not both"
    exit 1
}

if [string length $printer] {
    set endArg "| lpr -P$printer"
} else {
    set endArg ""
}
set geometry 600x450

exec sddshist2d $rootname.out $rootname.tx.h2d -col=t,x -xparam=300 -yparam=300
exec sddscontour -shade=32 $rootname.tx.h2d -quantity=frequency -device=png,onwhite -output=linac.tx.png

exec sddshist2d $rootname.out $rootname.txp.h2d -col=t,xp -xparam=300 -yparam=300
exec sddscontour -shade=32 $rootname.txp.h2d -quantity=frequency -device=png,onwhite -output=linac.txp.png


